### ISSUE TITLE
Feature: User can create a City Canvas pin to share a street art post 

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a City Canvas post to share the details of interesting street art they created or came across, including the artwork's title, artist name, an image, and a comment about the piece.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the 'Create a City Canvas Pin' page, the user will complete a form with the required text input fields and photo file upload field. Upon submitting the form,   

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 1 (1)](https://user-images.githubusercontent.com/85596835/155042540-0ad4b592-a555-47b8-92bf-850ed61f327e.png)

![Group 1 (2)](https://user-images.githubusercontent.com/85596835/155042813-cd49d252-12a2-443b-bffc-832c77d87b29.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` with City Canvas database tables created in DB Design
- [x] Update `data.sql` to insert one instance of dummy user data values into the `users` table and to insert a few instances of dummy post data values into the `posts` table
- [x] Verify all `schema.sql` and `data.sql` data was successfully created and visible in pgweb

### ☁️ Server

- [x] Update `server/index.js` to send a `GET` request to `/api/my-canvas-pins` endpoint to get all post data and:
  - [x] Handle all errors and respond to the client
  - [x] Test `GET` requests with HTTPie
- [x] Update `server/index.js` to send a `POST` request to `/api/create-pin` endpoint and:
  - [x] Require that all necessary database column data is included in the request
  - [x] Inserts new City Canvas post data into `posts` database
  - [x] Handle all errors and respond to the client with post data and `201` response status
  - [x] Test `POST` request with HTTPie

### ⚡ Client

- [x] Create an index.jsx component to mount application to `index.html` `#root` `div`
- [x] Update `app` component to be used to render visible components, verify added to `index.jsx`, and test with dummy `<h1>` data to ensure the page is actually rendering
- [x] Set up hash routing for `app` component and test with example `myCanvas` component
  - [x] Set up `notFound` component
- [x] Create a `navbar` component within `component directory` to be visible on all pages, including, `Home`, `My Canvas`, and `Art Finder` text for anchor placeholders
- [x] Update `app` component to return `navbar` component
- [x] Create a `myCityCanvas` page component within the `pages` directory that renders:
  - [x] `Create a City Canvas Pin` button
  - [x] `Card` bootstrap component for post previews
  - [x] A message if there are no user posts to render 
- [x] Update `app` component to render `page-container` and `myCityCanvas` page components 
- [x] Add static dummy data to `myCityCanvas` `Cards` and style according to wireframe
- [x] Once styled, update `myCityCanvas` component `state` to store post data in an array and user data in an array, and add dummy data to the arrays
- [x] Verify that `Card` components can render post previews with user data from `state` data
- [x] Update `myCityCanvas` component to include a `fetch` `GET` request at `/api/my-canvas-pins` endpoint and store post data from `posts` database in the `state` array
- [x] Update the `Card` component render to render posts previews from `state` data, with the newest post at the top of the rendered list
- [x] Create a `newPin` page component that renders a "New City Canvas Pin" `form` with the following input fields:
  - [x] Street Art Title `text` input
  - [x] Artist Name or Tag `text` input
  - [x] Street Art Photo `file` upload input 
  - [x] `Submit` button
- [x] Update `app` component and `state` to implement hash routing and switch between `newPin` component and `myCityCanvas` component
- [x] Update `navbar` component to add an anchor element to "My Canvas" and verify clicking takes the user to the "My City Canvas" page
- [x] Update the `myCityCanvas` component and add an anchor to the "Create a City Canvas Pin" button and verify clicking it takes the user to the `newPin` component`
- [x] Update `newPin` component to store form input data in `state`
- [x] Make a `fetch` `POST` request to `/api/create-pin` with data stored in `state` 
- [x] Test form to ensure new post is getting added to the database
- [x] Verify that new posts are being rendered properly on "My City Canvas Page"
- [x] Verify that refreshing the page keeps user on same page. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
