### ISSUE TITLE
Feature: User will be alerted if another user reported their post as 'removed from view' on the update page via modal to take action

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be alerted if another user reported their post as 'removed from view' on the update page via a modal and be prompted to take action on the post. The user can either update the post with accurate information or remove the post.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user's post has been reported as removed from view, when the user clicks on the post's update button, a modal will appear asking the user to either update the post with accurate information or to remove the post.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 7](https://user-images.githubusercontent.com/85596835/160948733-5f52b579-1f23-4be2-a517-bb4eb7acdf90.png)
![Group 6 (3)](https://user-images.githubusercontent.com/85596835/160948740-8829014d-051c-4dfa-8c82-94fbd10c7b8c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `PATCH` request to the `/api/remove-reported/:postId` endpoint which updates the post's reported column value to 'false'.
- [x] Update `server/index.js` so that the `PATCH` request to the `/api/pins/:postId` endpoint updates the pin's reported column value to 'false'.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create  a `ModalMarkedReported` component which accepts four props:  `show` which calls a `handleShowReported` method, `onHide` which calls a `handleCloseReported` method, `showDelete` which calls the existing `handleShow` method to display the `ModalDelete` component, and `reported` which relays a pin's reported value
- [x] Update `UpdatePinForm` component with a `handleShowReported` method which toggles the `showReported` state property to `true` and shows the `ModalMarkedReported` component if the pin's `reported` value is `true`, and style `ModalMarkedReported` according to the wireframe
- [x] Update `UpdatePinForm` component with a `handleCloseReported` method which toggles the `reportedModal` state property to `false` and closes the `ModalMarkedReported` modal
- [x] Update `UpdatePinForm` component's existing state `show` property and associated `handleClose` and `handleShow` methods with more concise verbiage as to what they represent and manipulate
- [x] Update `UpdatePinForm` component with a `removeReported` method which sends a `fetch` request to `/api/remove-reported/:postId` and updates the state's reported property to `false`
- [x] Update the `ModalMarkedReported` component so that the 'Update' button closes the modal
- [x] Update the `ModalMarkedReported` component so that the 'Delete' button displays the `ModalDelete` component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code, no longer need the `removedReported` method.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
