### ISSUE TITLE
Feature: User can save any post to their personal ‘My Saved City Canvas’ list

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save any post to their personal ‘My Saved City Canvas’ list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the heart icon on any dedicated post page to save the post to their ‘My Saved City Canvas’ list. The heart icon will appear electric blue in color when saved. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 5 (5)](https://user-images.githubusercontent.com/85596835/157781265-91075362-7ede-47a8-a6d4-b9ef19463165.png)

![Group 6 (1)](https://user-images.githubusercontent.com/85596835/157781259-d6f752e9-9efb-4d2c-a84a-e492538bbd2b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `POST` request to the `/api/save-post/:postId` endpoint to add the saved pin's `postId` and `userId` values to the `savedPosts` table and make sure both values are positive integers
- [x] Test `POST` request with the HTTPie
- [x] Update `server/index.js` so that the `GET` request to the `/api/pins/:postId` endpoint to also includes the data from the `savedPosts` table for that pin, or null if no data (not saved) using a left join
- [x] Test `GET` request with the HTTPie
- [x] Update `server/index.js` so that the `GET` request to the `/api/my-canvas-pins` endpoint to also includes the data from the `savedPosts` table for pins, or null if no data (not saved) using a left join
- [x] Test `GET` request with the HTTPie
- [x] Update `server/index.js` so that the `GET` request to the `/api/home-feed` endpoint to also includes the data from the `savedPosts` table for pins, or null if no data (not saved) using a left join
- [x] Test `GET` request with the HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `PinPage` component to create a `saveToFavorites` method that makes a fetch `POST` request to the `/api/save-post/:postId` endpoint  and add an `onClick` event to the heart icon which calls the `saveToFavorites` method
- [x] Change the color of the heart icon to electric blue if `saved` is a truthy value
- [x] Update `MyCanvas` component to pass the saved pin value to the `PostCard` component via props
- [x] Update `PostCard` component to add an electric blue heart icon to the card if the user saved the post according to the wireframe
- [x] Update `Home` component to pass the saved pin value to the `PostCard` component via props
- [x] Verify that electric blue heart icon is displayed according to the wireframe for both desktop and mobile screens

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
