### ISSUE TITLE
Feature: User can view saved posts on the ‘My Saved City Canvas’ page

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of all the posts they've saved on the 'My Saved City Canvas' page, with the most recently saved posts at the top of the list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the 'My Canvas' dropdown menu and select 'My Saved' pins to view their 'My Saved City Canvas' page. On the 'My Saved City Canvas' page, the user can view a list of saved post previews, with the most recently saved pins at the top. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` so that the `GET` request to the `/api/saved-posts` endpoint returns associated pin data needed for the `PostCard` component
- [x] Test the `GET` request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `SavedPins` page component and style base page component according to wireframe
- [x] Update `app.jsx` to include hash routing for `SavedPins`
- [x] Update `Navbar` component to link to `SavedPins` page component
- [x] Update `SavedPins` page component to render `PostCard` component with dummy data and style according to wireframe
- [x] Add state to the `SavedPins` page component and add dummy data and update `render` method to render `PostCard` components from state data
- [x] Update component to include a `componentDidMount` method that send a fetch request to the `/api/saved-pins` endpoint and store the returned pin data to state
- [x] Verify that feed displays according to wireframe successfully with fetch request with the most recently saved pins at the top
- [x] Display a message if there are no saved pins

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
