### ISSUE TITLE
Feature: User can remove saved posts from their 'My Saved City Canvas' page

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove saved posts from their 'My Saved City Canvas' page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'My Saved City Canvas' page, the user can click the 'View More' button to view the post's dedicated post page and then click the heart icon to remove the post from their saved posts list. The heart icon will appear grey when removed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 5 (7)](https://user-images.githubusercontent.com/85596835/158461972-7ed3630b-a498-45da-89f2-81444428d948.png)

![Group 5 (8)](https://user-images.githubusercontent.com/85596835/158461951-614ec774-0f8f-4cfc-873e-bf2a9bf923ee.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server

- [x] Update `server/index.js` to send a `DELETE` request to the `/api/delete-saved/:postId` endpoint and delete the specified post from the `savedPosts` table and:
  - [x] Make sure the `postId` is a positive integer
  - [x] Make sure that the `postId` is in the `savedPosts` table
  - [x] Make sure the user's `userId` and the post's 'saver' `userId` are the same
- [x] Test the `DELETE` request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `PinPage` component with a `toggleSaved` method that either fetches a `POST` request or a `DELETE` request based on the pin's `saved` property in state and then updates state with the appropriate `saved` and `saver` properties.
- [x] Update the `PinPage` component to update the `onClick` event for the heart icon that toggles the color of the heart to grey or electric blue based on if the post is saved, and calls the `toggleSaved` method.
- [x] Verify that the heart icon on the cards in the `MyCanvas` and `Home` feeds are not displayed after removal

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
