### ISSUE TITLE
Feature: User can view City Canvas pins near them on a map using geolocation

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view City Canvas pins near them on a map using geolocation. On the map, the user can click on a pin to view the pin's info window.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on 'Art Finder' in the navbar and view a map of City Canvas Pins near them. User can click on a pin to view the pin's info window from which they can click on the image to navigate to the post page, or click 'Get Directions' to get directions to the pin. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 3 (2)](https://user-images.githubusercontent.com/85596835/155897926-e87ecc51-dead-425b-8fce-00fe07ff26f3.png)
![Group 4 (1)](https://user-images.githubusercontent.com/85596835/155897929-ace723cf-b37e-4912-8542-5327f9a77bb9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to update `/api/home-feed` `GET` request to retrieve all post coordinates
- [x] Test the `GET` request with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an `ArtFinder` map page component that displays a map of City Canvas pin markers
- [x] Update `ArtFinder` map component by adding dummy pin information to state and render custom pins on the map from state data based on wireframe using Array.prototype.map() method
- [x] Add a geolocation button to the `ArtFinder` component
- [x] Send a fetch request to the `/api/art-finder` endpoint and store the fetched data in state using `setMarkers` hook
- [x] Update `App` component's hash routing to display the `ArtFinder` map page component
- [x] Update the `Navbar` component and link the `ArtFinder` map page component to the 'Art Finder' `Nav` link
- [x] Test and verify that each pin displays on map and displays info window when clicked. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
