### ISSUE TITLE
Feature: User can create a profile and log in to the application with a password

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a profile, complete with a profile photo, full name, email, and username, and log in to the application with a password. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the application's landing page, the user can create a profile by clicking on the 'New here? Sign up' link. The link will redirect the user to a sign-up form where they can enter their details to create a profile. Upon clicking submit, the user will be redirected back to the login page where they can enter their credentials to log in to the application. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 8 (1)](https://user-images.githubusercontent.com/85596835/166087336-033b8c9e-ee2b-4533-8335-adf8a1b0f951.png)
![Group 7 (1)](https://user-images.githubusercontent.com/85596835/166087349-ba15c2c2-640b-4486-b873-89a0b1820503.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add a `unique` constraint to the 'userName' column of the 'users' table

### ☁️ Server

- [x] Update `server/index.js` to require `argon2`
- [x] Update `server/index.js` to send a `POST` request to `/api/auth/sign-up` endpoint and:
  - [x] Require a username value and password value
  - [x] Require that password be at least 6 characters long
  - [x] Require that password include one number
  - [x] Require that username value is not already in `users` table
  - [x] Hash the password with `argon2.hash()`
  - [x] Insert the user's `username` and `hashedPassword` into the `users` table
  - [x] Test with HTTPie
  - [x] Handle all errors and respond to the client
- [x] Update `index.js` to require `jsonwebtoken` 
- [x] Send a `POST` request to `/api/auth/sign-in` and: 
    - [x] Require a valid username value and valid password value 
    - [x] Retrieve `userId` and `hashedPassword` from the `users` table in the sql query
    - [x] Verify `hashedPassword` and if the hashed passwords match, assign an object containing the `userId` and `username` to a variable called `payload`
    - [x] Call the `sign` method of JWT with two arguments, `payload` and the token secret
    - [x] Return the token and user payload 
    - [x] Test with HTTPie and handle all errors
- [x] Update `server/index.js` so that the `GET` request sent to `/api/my-canvas-pins` endpoint requires a user's `userId` parameter and test with HTTPie
- [x] Update `server/index.js` so that the `POST` request sent to `/api/post-pin` endpoint includes the logged in user's `userId` to post with accurate userId
- [x] Update `server/index.js` so that the `POST` request sent to `/api/auth/sign-in` endpoint retrieves the logged in user's `photoUrl` as well to be used for profile photo on `MyCanvas` page and test with HTTPie
- [x] Update `server/index.js` so that the `GET` request sent to `/api/saved-pins` endpoint requires a user's `userId` parameter and test with HTTPie
- [x] Update `server/index.js` so that the `POST` request sent to `api/save-post/:postId` requires the logged in user's `userId` in the request body and test with HTTPie

### ⚡ Client

- [x] Create a `Registration` page component 
- [x] Update  `App` component to set up hash routing for  `Registration` page component 
- [x] Style `Registration` page component according to wireframe
- [x] Create a `RegistrationForm` component which includes a React form with fields for 'First Name', 'Last Name', 'Email', 'Username', 'Profile Photo' and 'Password' fields
- [x] Render the `RegistrationForm` component within the `Registration` page component
- [x] Style `RegistrationForm` according to wireframe
- [x] Update `RegistrationForm` component to add state to store form data
- [x] Update `RegistrationForm` component to include a `handleChange` method which updates state form values with data entered into form fields as they change.
- [x] Update `RegistrationForm` component to include a `handleSubmit` method which:
  - [x] Creates a new `formData` object and appends form field data to the object
  - [x] Sends a fetch request with the request object's `method` property set to 'POST' and the body as the `formData` object
  - [x] Resets the component's state
- [x] Update `RegistrationForm` component so that the password, email, and username  `ClientErrors` from `index.js` get stored in appropriate error state properties to be used for validation messages
- [x] Update `RegistrationForm` component's 'handleSubmit' function to reset new state properties upon successful `POST` request
- [x] Create custom form validation for `email`, `password`, and `username` form inputs
- [x] Update `App` and `Registration` components to include hash routing for a `SignInForm` component
- [x] Create a `SignInForm` component which includes a React form with fields for 'Username' and 'Password'
- [x] Style `SignInForm` component to match wireframe
- [x] Update `SignInForm` component with an `handleChange` function to add form data in component state
- [x] Update `RegistrationForm` component to include a link to display the `SignInForm` component according to the wireframe
- [x] Update `SignInForm` component to include a link to display the `RegistrationForm` component according to the wireframe
- [x] Update `RegistrationForm` component's `handleSubmit` method form to redirect to `SignInForm` component's hash
- [x] Test that the form in `RegistrationForm` component functions properly: adds user info to `users` table, hashes password, and redirects to `SignInForm`
- [x] Implement React Context by: 
  - [x]  Creating an `app-context.js` file in the  `Client` -> `lib` directory which creates context and assigns it to the variable `AppContext` and exports it as default
  - [x] Updating the `App` component to: 
    - [x] Import `AppContext`
    - [x] Assign an object literal with the state's route value to the context variable `contextValue` in the `render` method of the component and wrap the return value in an `<AppContext.Provider>` element with the `value` attribute with a value of the `contextValue` variable
- [x] Update the token secret to prepare for user authentication 
- [x] Update the `App` component to prepare for user authentication and:
  - [x] Add `user` and `isAuthorizing` properties to the component's state object
  - [x] Create a `handleSignIn` method which will destructure a fetch result object (from the `SignInForm` component), and call the `setItem` method of the` localStorage` property of the `window` object with two arguments, the 'city-canvas-jwt' string and the `token` variable, and then add the `user` variable to the component's state.
  - [x] Update the render method of the component to include the state's user property and the `handleSignIn` method in the `contextValue` object 
- [x] Update the `Registration` page component to import `AppContext` and restructure the functional component as a class component with a `render` method that destructures the `handleSignIn` from context
- [x] Update `registration.jsx` file so that `AppContext` is assigned to the  `Registration` component's `contextType` property
- [x] Update `Registration` page component's `render` method by adding an `onSignIn` attribute with the value of `handleSignIn` to the `SignInForm` element
- [x] Update the `SignInForm` component with a `handleSubmit` method which: 
  - [x] Calls the `preventDefault` method of the event object
  - [x] Creates a request object with a `method` property with a value of 'POST' and a `header` property with a value of an object with a property of `'Content-Type'` with a value of `'application/json'`, and a `body` property with a value of the component's state stringified
  - [x] Sends a fetch request to `/api/auth/sign-in` and passes the result as the argument to the `onSignIn` prop passed from the `Registration` component from context assigned on the `App` component
- [x]  Update the `<Form>` element on the `SignInForm` component with an `onSubmit` event attribute with a value of `handleSubmit`
- [x] Update `SignInForm` component so that the password and username  `ClientErrors` from `index.js` get stored in appropriate error state properties to be used for validation messages
- [x] Update `SignInForm` component's 'handleSubmit' function to reset new state properties and form fields upon successful post request
- [x] Update `Registration` page component's `render` method to destructure `user` from context and redirect to the `Home` page component if the `user` variable is storing truthy data
- [x] Create a `decode-token.js` file in the `Client` -> `lib` directory and create a  function which:
  - [x] Splits the token at `.` and assigns the `encodedPayload` variable via array destructuring 
  - [x] Calls the `atob` function with the  `encodedPayload` variable as it's argument and assigns the return value to a `jsonPayload` variable
  - [x] Parses the the `jsonPayload` variable and stores the value in a `payload` variable, and returns the `payload` variable
- [x] Update `App` component's `componentDidMount` lifecycle method to get the locally stored JSON web token and store it in a `token` variable, and if there is a token, decode it using the `decodeToken` function and store it in a `user` variable, and update state's `user` property with decoded user data, and state's `isAuthorizing` property to `false`
- [x] Update `Registration` component's render method to check for user data in context, if user there is user data, redirect to `Home` component
- [x] Update `Home` page component to check for user data in context, if user there is no user data, redirect to `Registration` component
- [x]  -- Refactor: Update `App` component's `render` method to check for user data in the component's `state` object, and if there is no user data, redirect to `Registration` component
- [x] Create a `Redirect` component to redirect to the `Registration` component in other component's `render` methods when a user is not logged in. 
- [x]  --Refactor - Bug Fix: Update `App` component to remove valid user checks on the component, update all applicable components to check for user data in `context` and return a `Redirect` component to the `registration` hash if no user data is in context. Update all associated `componentDidMount` methods to only call `fetch` function if there is user data in context to prevent meaningless fetch calls on redirect
- [x] Update `NewPinForm` component to capture the logged in userID and send it with the fetch request
- [x] Update `MyCanvas` component authorization to display pins created by the specified logged in user saved to context
- [x] Update `MyCanvas` component to display correct user profile image from context
- [x] Update `SavedPins` component authorization to display pins saved by the specified logged in user saved to context
- [x] Update the `PinPage` component's `toggleSaved` method to send logged in user's `userId` in the fetch request to `/api/save-post/${this.props.postId}` to verify that the pin is saved by the logged in user
- [x] Update the `PinPage` component's `toggleSaved` method to send logged in user's `userId` in the fetch request to `/api/delete-saved/${this.props.postId}` to verify that the saved pin is deleted from the 'My Saved Pins' list by the logged in user
- [x] Update 'app' component with a `handleSignOut` method that removes the user's JSON web token from local storage and resets the `user` state property to `null`
- [x] Pass the `handleSignOut` method to context 
- [x] Update `AppNav` component by refactoring the functional component to be a class component
- [x] Include a `Sign Out` navbar option, and import context and assign `handleSignOut` function to the `onClick` event handler
- [x] Test navbar 'Sign Out' functionality.
- [x]  Update 'AppNav' component so that 'Nav' options collapse when app is being used on small screens utilizing 'Navbar.Toggle' and 'Navbar.Collapse' React Boostrap elements

### 🧑‍⚕️ Clean Up

- [x] Verify that state destructuring is consistent across all React `render` methods where applicable
- [x] Check all redirects and `location.hash` assignments and return the `Redirect` component where applicable
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
