### ISSUE TITLE
Feature: User can add the location of the street art when creating a post

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the location of the artwork in their posts by dropping a location pin via Google Maps API while the map is centered around their general location using geolocation. This will associate the post with the location they pin.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on the 'Create a City Canvas Pin' page, the user can double click on the map window to add a pin to the map marking the location of the street art pin they are adding. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 1 (6)](https://user-images.githubusercontent.com/85596835/155262806-f6f70ef8-704c-485e-9c17-b2b176958bae.png)

![Group 1 (5)](https://user-images.githubusercontent.com/85596835/155262812-e6cca8be-9c6e-4cb2-a6ca-2d8a411fe062.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Add the Google Maps API key to the `.env` file
- [x] Update `server/index.js` `POST` request to `/api/create-pin` end point to include `lat` and `lng` coordinate values captured from `newPinMap` component and require that they are number values.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `newPinMap` component that renders a google map via the Google Maps API with a zoom value set to 16 and:
  - [x] Add an `onClick` event to the `newPinMap` and a handler to capture the associated `lat` and `lng` coordinate values add those values to `state` 
  - [x] Update the `onClick` event to place the `Marker` component on the clicked location 
  - [x] Create a custom marker icon to match the wireframe and update the `Marker` component's icon prop with the custom marker icon
  - [x] Verify only one custom marker can appear on the map when a user clicks the map
  - [x] Add a button to center the map based on user location using geolocation 
- [x] Add the `NewPinMap` component to the `NewFormPin` component
- [x] Update the fetch request on `NewFormPin` to add the `marker` state data
- [x] Verify that the page styling matches the wireframe
- [x] Redirect the user back to the "My City Canvas Page" upon form submittal
- [x] Test the "New City Canvas Pin" page form and map and verify that the newest posts are appearing at the top of the "My City Canvas" page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
