### ISSUE TITLE
Feature: User can update their City Canvas posts

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can access the posts they’ve created from the 'My City Canvas' page to update them with more info, a better photo, more precise location, etc., using an update form modeled after the post form which will overwrite the post's previous data. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the update button on any of their own City Canvas posts and update the information and/or image of any post via the update form. Clicking submit on the form will save and update their post, and redirect them back to the 'My City Canvas' page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 4 (2)](https://user-images.githubusercontent.com/85596835/156842687-b4a0d27f-a245-47c8-bd08-99a1ce68fc7f.png)

![Group 5](https://user-images.githubusercontent.com/85596835/156843028-678a253d-0823-458a-83ef-aca4a5249aaa.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `GET` request to the existing `/api/pins/:postId` endpoint to get all the necessary data for state and to prepopulate the update form and:
- [x] Update `server/index.js` to send a `PATCH` request to the `/api/pins/:postId` endpoint to update the specified post's data in `posts` table, and: 
  - [x] Ensure that `postId` is a numerical value greater than 0
- [x] Test `PATCH` request with HTTPie
- [x] Test postId `GET` request to ensure that updates stuck
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an `update-pin` page component that renders a form to update a specified user's pin post and:
  - [x] Render an `update-form` similar to the `new-pin-form`
  - [x] Add some dummy data to component state based on a specified pin 
  - [x] Prepopulate all the text form fields with data from the specified post stored in state
  - [x] Pre-pin the map with dummy data coordinates
- [x] Create a `componentDidMount` method that sends a fetch `GET` request for the specified pin data and sets the data to state
- [x] Verify pre-populated form data still renders properly
- [x] Create a `handleSubmit` method that:
  - [x] Sends a fetch request with `PATCH` method and update state with new post data
  - [x] Redirects user back to `my-canvas` page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
