### ISSUE TITLE
City Canvas User Interfaces: Clean Up

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#33]
### ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Buttons, Clickable Icons, and Links - Verify that each interactive element on the site looks and feels interactive:
    - Links should be colored differently from surrounding text (if text is dark, the default blue usually works) to stand out. Hovering over a link should change the `cursor` to a `pointer`, and:
        - If the link only contains text (including font-based icons), either change the link's `color` or add/remove an `underline`.
        - If the link contains non-text content (such as an image), change the link's appearance in some way (`color`, `text-decoration`, `outline`, `box-shadow`, `background-color`, etc.). Make sure the link's overall size and position don't change.
    - Buttons should clearly stand out from the surrounding content, using a different `background-color` and/or a `border`. Hovering over a button should change the `cursor` to a `pointer` and change the button's appearance in some way (`color`, `text-decoration`, `outline`, `box-shadow`, `background-color`, etc.) without changing the button's overall size or position.
    - If a single link/button and a single input are associated with each other, while the user is `:focus`ed on the input, pressing Enter/Return should trigger the link/button.

- [x] Mobile-First Responsive Design - Verify the site's layout fits and effectively uses space on all commonly-used device sizes, including:
    - Smartphone portrait orientation (less than 768px wide) - All of the CSS should assume this width by default.
    - iPhone X (portrait and landscape)
    - iPhone SE 2 (portrait and landscape), aka iPhone 6/7/8
    - iPad/Tablet (portrait and landscape), 768px wide or more - `@media screen and (min-width: 768px)` media query to override your styles where necessary
    - Wide-screen Desktop/Laptop (1920px-by-947px, 1280px wide or more) - `@media screen and (min-width: 1280px)` media query to override styles where necessary.
    - Fluid Layout - Between breakpoints, UI should fluidly expand to fill the width of its container. Use `max-width` (in pixels) on page container to prevent columns from expanding to an awkward width. Use percentage width for columns. 
    - Pass The Wiggle Test ™ - Verify no bottom scroll bar will ever exist.

- [x] Remove All Placeholder Links and Buttons

- [x] Network Activity:
  - [x] Verify that each API request (that isn't part of initial page load) handles network wait times and failures gracefully (test using inspector Network tab):
    - Send the request for data...
    - While an API call is in-progress, a loading message or animation (spinner) should be displayed and related buttons should be disabled. Test spinner by artificially slowing down the browser's networking via developer tools.
    - When the API call stops (regardless of outcome), the loading message/spinner should disappear, and related buttons should re-enable (if they're still being displayed).
    - When a `GET` API call responds with an empty data set (no error), the client should display an appropriate message.
    - When an API call loses connection before completing, the client should let the user know there was a connection issue.
    - When an API call produces an error response, the client should communicate it to the user appropriately.
    - Regardless of the type of network failure, users should be able to easily retry the request without navigating back to the page or re-entering a bunch of form information.
  - [x] Optimize graphics, make sure they load fast, consider using cloudconvert to optimize JPG and PNG images to WEBP files. 
  - [x] Display messages, CTAs, and click targets for empty lists and search results.
  - [x] Network Errors - display an apologetic error message to the user explaining that something went wrong with the request and that they should try again later. This message must be visible to users without opening the developer tools.
    - Test with a simulated disconnected network (offline) using browser's dev tools. 

- [x] Check your App on a Mobile Device and Fix any issues.

- [x] Fix any typos

- [x] Create a Demo User
  - [x] Pre-seed database with a demo user account. 
  - [x] Pre-fill login form with credentials that the app will accept.
