### ISSUE TITLE
Refactor: Prepare source code for automatic deployment

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#35]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Refactor 'uploads-middleware' to write image uploads to a temporary directory for processing
- [x] Refactor '/server/index.js' so that all Express PUT and PATCH requests that include image uploads processes images stored in the '/.tmp' file with sharp and then upload to AWS S3 bucket folder using 'aws-sdk/client-s3' package and test.
- [x] Upload all database post and profile images to AWS S3 bucket and update the 'data.sql' file. 
- [x] Remove all local post and profile image files that were replace with AWS S3 URLs
- [x] Verify that  'build' script completes and exits cleanly without errors.
- [x] Verify that 'server/' code does not have any hard-coded configuration in it, including database URLs, port numbers, and API keys. 
- [x] Verify that ' client/' code does not refer to localhost anywhere, or have any hard-coded API keys in it.
- [x] Verify that link and script tags are not relative URLs.
- [x] Verify that 'start' script does not use a watcher.
- [x] Verify that database schema can be rebuilt properly in one step.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface still looks natural on both mobile and desktop screens.
- [x] Merge deployment-prep branch.
