### ISSUE TITLE
Feature: User can delete a City Canvas post they created

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete any of the City Canvas posts they’ve created from the 'Update City Canvas' page by clicking on the delete button, and confirming deletion in the deletion modal. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on the 'Update City Canvas' page, the user can click the delete button to delete their post from City Canvas. After clicking delete, a modal will appear asking the user to confirm post deletion. Clicking cancel will close the modal and keep the user on the 'Update City Canvas' page. Clicking delete will close the modal, delete the post, and redirect the user back to the 'My City Canvas' page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 4 (5)](https://user-images.githubusercontent.com/85596835/156856386-42407594-fc43-4e80-9512-3f6255086dc4.png)

![Group 5 (4)](https://user-images.githubusercontent.com/85596835/156856433-dbd591be-92d4-4cfd-a10f-74e226ea5759.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `PATCH` request to the `/api/delete-pin/:postId` endpoint and:
  - [x] Checks to make sure the `postId` number is a positive integer
  - [x] Sets the pin's `deleted` value in the `posts` table to the current date/time
- [x] Test `PATCH` request with HTTPie
- [x] Update existing `GET` requests to only retrieve posts with a `deleted` value of `null`
- [x] Test all the `GET` requests with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `UpdatePinForm` component to include a `Delete` button next to the `Submit` button
- [x] Create a React Bootstrap modal component which appears when the `Delete` button is clicked
- [x] Within the modal content, add a `Delete` button and a `Cancel` button
- [x] Create a `deletePin` method which listens for a click, and
  - [x] Sends a `PATCH` fetch request to `/api/delete-pin/:postId` 
  - [x] Redirects user back to 'My Canvas' page
- [x] Add and `onClick` event to the modal's `Delete` button that calls the `deletePin` method
- [x] Verify that the deleted pin does not appear in the home feed or on the 'My Canvas' feed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
