### ISSUE TITLE
Bug: Database Overwrite

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#41]
#### Desired Behavior

> ##### The app should not import database schemas and data, thus overwriting the database on the deployed application. 

#### Actual Behavior

> ##### The app currently runs the `db:import` script upon deployment and overwrites the database for the deployed application with data on the 'database/schema.sql' and 'database/data.sql' files. This deletes any new user data in the deployed application.

#### Steps to Reproduce

> ##### To trigger the bug, you must push the master branch to dokku, or set dokku config variables. Simple deployment or updates to the deployed application trigger the script to run.

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Research issue in npm, webpack, and node docs 
- [x] Test various hypotheses:
  - [x] Use a conditional in the `db:import` value in 'scripts' value in 'package.json'.
  - [x] Update the 'procfile' to remove the release command that triggers the database import.
- [x] Once a solution is found:
  - [x] Submit PR
  - [x] When solved, after clean up below, merge PR.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
