### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#43]
# README.md for City Canvas

Complete a README.md for City Canvas while following the provided guide.

## ✅ Task List

- [x] Double check that my README includes the following sections:
  - [x] the project name
  - [x] a brief description
  - [x] a brief paragraph explaining why you wanted to build this project.
  - [x] a link to the live deployment of the project
  - [x] 1-2 gifs of the most interesting features of the application
  - [x] list of technologies used including databases, languages, libraries, and frameworks.
    - If your project uses any external APIs, then list them and link to their documentation.
  - [x] finished and implemented features list
  - [x] stretch features list, up to 3
  - [x] system requirements for developers that would like to run the code on their computer
  - [x] a detailed set of instructions for getting started, including:
      - Installing all dependencies using npm, etc.
      - Creating any necessary configuration files.
      - Any external services or accounts that need to be set up, such as 3rd-party APIs or cloud services like S3.
      - Updating any custom environment variables, if necessary.
      - Running any necessary build scripts.
      - Creating a database, if necessary.
      - Importing any necessary database files.
- [x] Check all spelling and grammar.
- [x] Open a Pull Request.
- [x] Send link to the Pull Request to my portfolio reviewer / instructor.
