### ISSUE TITLE
City Canvas Project Polish

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#45]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Find and address all typos in the project's README and source code.
- [x] Give the project a custom name, according to the guide. The `<title>` should fall in line with the site's overall purpose. `Final Project` is not specific enough.  
- [x] Use the new name everywhere:
  - [x] repository name
  - [x] local clone
  - [x] Dokku app name
  - [x] resume link(s)
  - [x] LinkedIn profile link(s)
  - [x] all other links
  - [x] <title> tags in HTML
- [x] Update repository "About" section. 
- [x] Use a custom `favicon`, and make sure it matches the site's theme.
- [x] Remove any unprofessional content.
- [x] Make the project sharable using Open Graph `<meta>` tags
- [x] Open a Pull Request.
- [x] Merge the Pull Request.
