### ISSUE TITLE
Bug: Twitter Summary Card With Large Image for City Canvas Not Displaying Image

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#47]
#### Desired Behavior

> ##### The app should render a Twitter summary card with a large image.

#### Actual Behavior

> ##### The app only renders the title and description on the Twitter summary card with a large image. The image doesn't appear. 

#### Steps to Reproduce

> ##### To trigger the bug, you must open the [Twitter Card Validator](https://cards-dev.twitter.com/validator), or simply paste the like to City Canvas in a tweet draft on Twitter when logged in. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Test using the Twitter `<meta>` tag for the image in addition to the Open Graph `<meta>` tag for the image. 
- [x] ~~Test with a 2:1 image ration instead of a 1.9:1 image ratio.~~
- [x] ~~Test with a different image format.~~
- **Clean Up**
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
