### ISSUE TITLE
Feature: User can view a feed of recent post previews by all City Canvas users

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a feed of recent post previews from users on the 'Home' page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on 'Home' in the navbar to view a feed of other users' recent City Canvas post previews. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home Page_ Feed](https://user-images.githubusercontent.com/85596835/155393246-93cb8850-265c-4e82-8477-8857c44fc159.png)

![Home Page](https://user-images.githubusercontent.com/85596835/155393253-c3ffe1a9-b1ed-46bb-ba94-7cb313c76849.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to include a two other users
- [x] Update `data.sql` to include at least one post from the two new users
- [x] Verify all updates to `data.sql` were successfully created and visible in pgweb

### ☁️ Server

- [x]  Update server/index.js to send a `GET` request to `/api/home-feed` endpoint to get all users' post data and:
  - [x] Test if I can get data from both the `posts` table and the `user` table
  - [x] Test `GET` requests with HTTPie
  - [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `Home` page component that renders:
  - [x] `PostCard` component for post previews
- [x] Update `Home` component state to store `post` table data in an array and `users` data in an array, and add dummy data to the arrays to verify styling matches the wireframes
- [x] Update `Home` page component to pair accurate user information with each post
- [x] Update the `PostCard` component render to render the appropriate button text on the `Home` component cards vs. the `MyCanvas` component cards
- [x] Update `Home` component to include a fetch `GET` request at /api/home-feed endpoint and store post data from `posts` and user data from `users` databases in the state arrays
- [x] Verify that `Card` components can render post previews with user and pin data from `state` data
- [x] Verify that newest posts are at the top of the  `Home` component feed. 

### 🧑‍⚕️ Clean Up

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
