### ISSUE TITLE
Feature: User can view complete post information

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User view another user's complete post information on a dedicated post page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the 'View More'  button on any post in the home feed and view that post's complete information on a dedicated post page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 2 (1)](https://user-images.githubusercontent.com/85596835/155458088-197b0575-9660-42ac-be37-a69a59772ac6.png)

![Group 3](https://user-images.githubusercontent.com/85596835/155458093-ea073cf5-3ecd-404b-aed8-60bb4576d9d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to to send a `GET` request to /api/pins/:postId endpoint and return selected pin information
- [x] Test with HTTPie
- [x] Handle all errors, including client errors, and respond to the client

### ⚡ Client

- [x] Create a `PinPage` component to render dedicated post information and style static dummy data as shown on the wireframes
- [x] Update `App` component's render method to accurately handle hash changes based on postId value 
- [x] Add some dummy data to state and verify render method works from state data
- [x] Add fetch request to `PinPage` component and store data in state
- [x] Update `PostCard` component to link `ViewMore` button to appropraite `PinPage`
- [x] Verify page renders as expected according to wireframe

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
