### ISSUE TITLE
Feature: User can view the map pin location of a post 

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the map pin location of a post on a dedicated map page using the Google Maps API. Clicking on the pin will display an info box with an image of the street art that redirects back to the post page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From a dedicated post page, user can click on the 'On The Map' link and view the pin's location on a map. User can click on the map pin to see an image of the pinned street art and can click on the image to be redirected back to the post page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 3 (1)](https://user-images.githubusercontent.com/85596835/155654778-03405d25-af42-4d53-8585-ad68442ea3c5.png)

![Group 4](https://user-images.githubusercontent.com/85596835/155654785-75ca8147-89e8-42c1-84b4-c6a9f8add041.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a `PinMap` component to render a map with a zoom of ~16 around the associated post's location
- [x] Update `App` component to add hash routing with `PinMap` component and test render
- [x] Add a custom map pin to render at post's `lat` and `lng` coordinates 
- [x] Edit `PinMap`'s `props` to get latitude and longitude coordinates from hash route
- [x] Update hash route and props to include image url
- [x] Add an info window to the pin that appears when the map pin is clicked
- [x] Add a thumbnail image of the associated post's image to the info box
- [x] Link the thumbnail image to reroute back to the post's dedicated page
- [x] Update `PinPage` component to route 'On The Map' link to associated `PinMap` component
- [x] Add a link to the info window to redirect to a Maps URL to get google directions to pin location

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
