### ISSUE TITLE
Feature: User can mark other users' posts as removed from view

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/city-canvas#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can mark other users' posts as removed from view if the street art is no longer visible at the City Canvas pin location. This will visually mark the post as reported so all users can see that it's been reported. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While on another user's dedicated post page, user can click on the 'Report as removed from view' link, confirm that they want to report the City Canvas pin in a confirmation modal, and see that the pin has been reported in the home feed and on the post page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Group 6 (2)](https://user-images.githubusercontent.com/85596835/160464077-3dc951d1-3311-4906-8ae1-46e02a9a3801.png)
![Group 5 (10)](https://user-images.githubusercontent.com/85596835/160463393-caf1cc16-d28e-4cc2-8560-10940aa81bc0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `PATCH` request to `/api/report/:postId` and update the `reported` column in the `posts` table with a value of true
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `PinPage` component and add a `reportPin` method which:
  - [x] Sends a fetch request to `/api/report/:postId` with a `method` property with a value of `patch` 
  - [x] Updates `PinPage` component state's `pin` object with a `reported` property and the associated value from 'posts' table
- [x] Create a `ModalReport` component, which accepts two props, `show` which calls a `handleShow` method, and `onHide` which calls a `handleClose` method, and style according to the wireframe
- [x] Make sure that the `ReportModal` `Cancel` button closes the modal and takes no action
- [x] Update `PinPage` component so that when the 'Report as removed from view' link is clicked, the `ReportModal` appears
- [x] Update the `Report` button on the `ReportModal` with an `onClick` event that calls the `reportPin` method from the `PinPage` component via props
- [x] Update `PinPage` component so that the render method  displays 'Reported as removed from view' warning in orange soda colored font instead of the 'report as removed from view link' if reported state is not set to null.
- [x] Update `PostCard` component to display an exclamation icon and prohibition eye icon according to wireframe if the `reported` property of component  state object has a value other than `null`

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
